### PR TITLE
Added cargo.json file for constant variables

### PR DESCRIPTION
**Pull request by Hemant2A2**
image
Added the above constants in main.rs to config.json

### CODE REVIEW

**Comment by darshi1337** [comment]
@Hemant2A2 
Is this compiling in your system?

**Comment by Hemant2A2** [comment]
Yes, it is compiling but there are warnings regarding unused variables and to use snake_case_naming inside `struct Config`

**Comment by darshi1337** [comment]
image
@Hemant2A2 Getting this error

**Comment by darshi1337** [comment]
@Hemant2A2 
You can contribute more on this as well.

**Pull request merged**
